### ISSUE TITLE
Commands in the example are out of date

### ISSUE THREAD

**Issue by timurista** [ldemailly/go-flagz#14]
etcdctl uses put now not set
https://github.com/ldemailly/go-flagz/blob/7d437ddd40d446d5e85c1aa87cecf95a07341c5a/examples/server/README.md#L9

see etcdctl version [ >= 3.4.9](https://github.com/etcd-io/etcd/releases/tag/v3.4.9)

**Comment by ldemailly** [comment]
the whole etcd part is not working/tests aren't working 
https://github.com/mwitkow/go-etcd-harness/issues/1 
I wonder if maybe it'd be simpler to just drop that functionality to reduce dependencies and just stick to file based/configmap updates as that's working

**Comment by timurista** [comment]
If we drop functionality maybe delete the examples then? as it's a bit of misdirection

**Comment by ldemailly** [comment]
yes I just didn't have time to check if it's just a simple fix or not to get it back working; focused on getting configmap use case working instead (on my free time) - we can figure it out offline/depending on bandwidth and needs

**Comment by timurista** [comment]
@ldemailly can we merge in #17 and close this out?

**Comment by timurista** [comment]
we can just direct people to use http_server example for now

**Comment by ldemailly** [comment]
- examples/server is the etcd that can use the updates you made from set to put... and I haven't tested if it works or not (have you?)
- examples/server_kube is using configmap, which are working, and indeed has no doc; but what you put in the PR is the wrong doc

**Comment by timurista** [comment]
ok, I can remove the etcd steps for server_kube as that part is wrong. But the `run .` part worked.

**Comment by ldemailly** [comment]
if you want github to autoclose you can put "Fixes #14" or some such (but not Fixes issues: #14)

**Comment by timurista** [comment]
Ah, thanks! I put `fixes issues: ...` in the body

**Comment by ldemailly** [comment]
the magic keyword can be in the body, but just use "Fixes #nn" (without inserting issues:)
